---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: AWS_CLUSTER_NAME
  version: "K8S_VERSION"
  region: AWS_REGION

managedNodeGroups:
- name: AWS_CLUSTER_NAME-mng
  desiredCapacity: 4
  minSize: 0
  maxSize: 5
  instanceType: EC2_INSTANCE_TYPE
  